---
- hosts: dev
  gather_facts: true
  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
  roles:
    - webserver
    - node
    - clone
    - build
    - runner
