- name: Download and install NVM
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
  args:
    creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'

- name: Ensure nvm is sourced in .bashrc
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    line: 'export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    insertafter: EOF

- name: Install Node.js via NVM
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install 20
    nvm alias default 20
    nvm use default
  args:
    executable: /bin/bash

- name: Install Pnpm
  ansible.builtin.shell: |
    curl -fsSL https://get.pnpm.io/install.sh | bash -
  args:
    executable: /bin/bash
    creates: '{{ ansible_env.HOME }}/.local/share/pnpm'

- name: Install PM2 via npm under NVM
  become: false
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm install -g pm2
  args:
    executable: /bin/bash
